Update deploy-prod.yml

diff --git a/.github/workflows/deploy-prod.yml b/.github/workflows/deploy-prod.yml
--- a/.github/workflows/deploy-prod.yml
+++ b/.github/workflows/deploy-prod.yml
@@ -40,10 +40,9 @@ jobs:
         run: |
           CODE=`curl --write-out '%{http_code}' --silent --output /dev/null "${{ secrets.API_HOOK_URL }}"`
           echo "$CODE"
-          if [ $CODE!=200 ];
+          if [ $CODE!="200" ];
           then
-            echo "FAILURE"
-            exit 1
+            echo "FAILURE" && exit 1
           else
             echo "SUCCESS"
           fi
